Tarea1 terminada v1
Oscar992/Tarea1Maven pull request #1
Opened 2023-04-13 14:00 UTC by Oscar992

2023-04-13 16:38 UTC, calvarioTeacher31 requested changes

2023-04-13 16:38 UTC, calvarioTeacher31 commented on src/main/java/classes/Enemigo.java
>  package classes;
el paquete no se tiene que llamar "classes" usa la convención model como en clase

2023-04-13 16:38 UTC, calvarioTeacher31 commented on src/main/java/main/Main.java
> +        log.info("Ejercici05 \n");
no es necesario el \n en los logs

2023-04-13 16:38 UTC, calvarioTeacher31 commented on src/main/java/main/Main.java
> +    static void ejercicio1(Faker faker, Logger log) {
crea un paquete llamado "ejercicios" y pon cada uno en una clase

2023-04-13 16:38 UTC, calvarioTeacher31 commented on src/main/java/main/Main.java
> +            var enemigo = new Enemigo(id);
esto son constantes

2023-04-13 16:38 UTC, calvarioTeacher31 commented on src/main/java/main/Main.java
> +            log.debug(new Formatter().format("Enemigo %d ", listEnemigos.get(i).getId()).toString());
no es necesario esto, en clase expliqué cómo formatear los log dbug sin necesidad del formatter ni string format

2023-04-13 16:38 UTC, calvarioTeacher31 commented on src/main/java/main/Main.java
> +            var enemigo = mapEnemigos.get(faker.number().numberBetween(1, 150));
final var

2023-04-13 16:38 UTC, calvarioTeacher31 commented on src/main/java/main/Main.java
> +    }
final var, usar los logs formateados, no es necesario \n

2023-04-16 18:36 UTC, calvario-31 commented on src/main/java/ejercicios/Ejercicio1.java
> +                    enemigo.isEsTerrestre());
crea un metodo to string para reducir eso

2023-04-16 18:37 UTC, calvario-31 commented on src/main/java/ejercicios/Ejercicio2.java
> +        Logs.info(Arrays.toString(new ArrayList[]{listNumbers}));
lo que estás haciendo es lo siguiente:

- creas un array list
- casteas el array list a array
- imprimirs como string

si ya tienes una lista imprime la lista de frente no recastees a rray

2023-04-16 18:38 UTC, calvario-31 commented on src/main/java/ejercicios/Ejercicio3.java
> +        Logs.info(Arrays.toString(new ArrayList[]{listString}));
lo mismo que arriba

2023-04-16 18:38 UTC, calvario-31 commented on src/main/java/model/Enemigo.java
> +        return sb.toString();
ya tienes este método úsalo para loguear el enemigo. No te sugiero ponerlo uno en cada línea porque los logs van a salir enormes. Ponlo todo en una sola línea separado con espacios

2023-04-17 21:28 UTC, calvario-31 approved these changes

2023-04-17 21:30 UTC, merged